---
- hosts: all
  become: yes
  tasks: 
    - name:  to install webserver on ansible node
      apt: 
        name : apache2
        state : present

    - name: i want webserver on Ubuntu
      service:
        name : apache2
        state : started